# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47912d9929c1dfe75c0d006c216bd795fa85e942fd03361f759e8cec8c389f8d053d82e8194c10483366e3a225748de3fccc3c679175e07863a84ff89eba6fb1

test:
  secret_key_base: 7295f6d0dbebd6262344f9ef64e41bb97f04bbe5fbe286d97fa783aef29a120fb94342c3b1ccc1f46140247868143521090e7b1df951560c24c41eec63733ac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
